name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 1 * * 1'
    - cron:  '0 2 * * 2'
    - cron:  '0 3 * * 3'
    - cron:  '0 4 * * 4'
    - cron:  '0 0 * * 5'
    - cron:  '0 3 * * 6'
    - cron:  '0 1 * * 0'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
      - name: Sleepy
        run: sleep ${RANDOM:0:2}m
  
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python==4.5.4.60
          pip install easyocr pillow numpy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
      - name: run
        run: STD_ID=${{ secrets.STD_ID }} PASSWORD=${{ secrets.PASSWORD }} python3 main.py
